platform :ios, '8.0'
pod 'FXBlurView'
pod 'IQDropDownTextField'
pod 'JVFloatLabeledTextField'
pod 'FlatUIKit'
pod 'RNGridMenu'
pod 'JVFloatingDrawer'
pod 'VBFPopFlatButton'
pod 'REMenu'
pod 'TOMSMorphingLabel'
pod 'GRKBarGraphView'
pod 'DIDatePicker'
pod 'PNChart'
pod 'MZFormSheetController'
