platform :ios, '8.0'
pod 'AFNetworking', '~> 2.0'
pod 'JSONModel'
pod 'SDWebImage', '3.7.1'
pod 'CHTCollectionViewWaterfallLayout'
pod 'MMProgressHUD'
pod 'UIFloatLabelTextView'
pod 'AwesomeMenu'
pod 'FXBlurView'
pod 'SWTableViewCell'
pod 'IQDropDownTextField'
pod 'AXRatingView'
pod 'RNFrostedSidebar'
pod 'CSGrowingTextView'
pod 'JVFloatLabeledTextField'
pod 'SVProgressHUD'
pod 'SVPullToRefresh'
pod 'FlatUIKit'
pod 'RNGridMenu'
pod 'CNPGridMenu'
pod 'JVFloatingDrawer'
pod 'VBFPopFlatButton'
pod 'REMenu'
pod 'PNChart'
pod 'TOMSMorphingLabel'
pod 'MZFormSheetController'
pod 'GRKBarGraphView'
pod 'DIDatePicker'
